### PR TITLE
Login and UKI updates

### LINKED ISSUE #352: Gnome-keyring not creating default keyvault, 1Password MFA issues
I use MFA with 1Password and by default it doesn't appear that gnome-keyring is set up to work with Hyprland fully. 1Password is unable to save the token after I enter my MFA code (on my personal account) or after I complete a Duo MFA (on my work account) challenge. 

Specifically, when logging in it's not (at least on my system) initializing a default keyring (I have no keyrings at all). I was able to prove this by checking ~/.local/share/keyrings/, which is empty as well as running `secret-tool store --label="Test" testkey testvalue` which prompts me to set a password for "Default keyring". I see that gnome-keyring was added to the Yay install command in xtras.sh at some point and that a migration file exists to add it to older installations. I've replicated this on multiple virtual machines as well. 

Creating a keyring with Seahorse and making it the default does allow 1Password to save the MFA tokens. However, that keyring does not automatically unlock when first logging into the system.

I'm investigating steps to effectively address this on an alternate and virtual machines. So far I've only succeeded in breaking LUKS encryption and bricking the install. That said, I hope to develop a solution this weekend.

### LINKED ISSUE #372: Better Default Configuration for Managing SSH Keys and Secrets
SSH keys are an excellent way to manage multiple accounts, such as separate GitHub profiles for work and personal use. Many distributions already integrate SSH key management with their system secret managers, such as [GNOME Keyring](https://wiki.archlinux.org/title/GNOME/Keyring), to simplify this process.

I propose offering a similar default configuration for handling secrets in this way. The system should unlock the "keyring" automatically upon user login. Also, there should be a way for prompting passwords when required, or when storing new secrets, by using a tool similar to askpass.

### LINKED ISSUE #1015: After installing VSCode and login in to GitHub there's a missing OS keyring error
The specific error says:

> An OS keyring couldn't be identified for storing the encryption related data in your current desktop environment.

It says to [troubleshoot using this guide](https://code.visualstudio.com/docs/configure/settings-sync#_troubleshooting-keychain-issues) or use a weaker encryption.

### LINKED ISSUE #1619: Multiple Lenovo types not able to boot / get in to BIOS after installation
### System details

Lenovo m720q (M1UKT77A BIOS)

### What's wrong?

I installed Omarchy 2.0 on a Lenovo m720q succesfully. However, during the reboot the machine hangs on the Lenovo logo and I'm unable to get in to the BIOS even. Disconnecting power didn't help.
I reproduced this on 2 Lenovo m720q's, as I thought it might be a quirky machine I grabbed another to try on.

Looking at #1286 it might be there is a Lenovo specific issue?

I will try a CMOS reset and report back after.

Image

### LINKED ISSUE #1719: New installs sometimes end up with Limine instead of Omarchy as the #1 boot loader entry
### System details

All

### What's wrong?

We should always start with Omarchy instead of Limine as the #1 boot loader entry.

### LINKED ISSUE #2203: [Bug] Persistent Keyring prompt on every Brave browser launch.
### System details

AMD Ryzen 7 7800X3D, NVIDIA 4080 SUPER, Omarchy Latest (3.0.2)

### What's wrong?

On every launch, Brave prompts for the GNOME Keyring password.
**Brave belongs to the same keyring as the default Chromium**.  Chromium does not ask for access to keyring, but Brave does. I don't know why. I checked the flag settings, as well as the configuration files for both browsers - everything seems to be identical. 

Brave Version : 	1.83.109 Chromium: 141.0.7390.55 (Official Build) (64-bit) 
Chromium Version:  140.0.7339.207 (Official Build)

**Note**
From what I can see, I'm not the only struggling wit this problem: https://discord.com/channels/1390012484194275541/1421504252299186208

--- 

Image

### PR DESCRIPTION
**Pull request by ryanrhughes**
Original #1860

- Changes from using Omarchy Seamless Login DM to SDDM with Autologin
- Update to use custom named UKI to (hopefully) resolve issues due to long filename (Fixes #1619)
- Update UKI install rules to always prioritize (Fixes #1719)
- Remove Archinstall created Limine EFI entry
- Create a default keyring to house 2FA tokens and other items (Fixes #352) (Fixes #372)
- Updates VSCode installer to ensure it uses the default keyring (Fixes #1015) (Fixes #2203)
- Adds guards for BTRFS and Limine
- Drops install support for alternate bootloaders

### A note about the default keyring 
This keyring is created with no password so it can be unlocked on boot without any user intervention. This relies entirely on LUKS encryption to provide protection for this info but given the only thing that should exist in here are 2FA tokens and / or SSH keys that would otherwise persists on disk, this is fine to me. There's nothing stopping a user from adding a password to their keyring if they'd prefer that but because we don't present an actual login screen outside of LUKS, the password can't be captured to unlock the keyring.

The alternative path here would be #631 which I ran personally and did work well but is a bit of a non-standard approach.

### Dropping support for alternate bootloaders
At this point, there's no reason someone should be installing fresh with anything but Limine. Because of this, I'm proposing here that we drop it from the install so as to simplify the complexity and permutations of installs we have to deal with.

As a part of this, it was added to the guard in the event someone does a manual install with the wrong bootloader chosen. They could still technically do it but they're on the hook for their own hooks and configs.

### AMI Bios Fix
The change to the UKI name _should_ fix the issue we were having with AMI BIOS based on the testing I had some users do a while back. The actual install here has not been tested yet as we haven't found a volunteer.

### CODE REVIEW

File: install/login/default-keyring.sh [hunk 1]
```diff
@@ -0,0 +1,20 @@
+KEYRING_DIR="$HOME/.local/share/keyrings"
+KEYRING_FILE="Default_keyring.keyring"
+DEFAULT_FILE="default"
+
+cat << EOF | tee "$KEYRING_FILE"
```
Comment (y0no) [inline install/login/default-keyring.sh:5]: KEYRING_FILE need to be concatenated with KEYRING_DIR no ?

File: install/login/default-keyring.sh [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+[keyring]
+display-name=Default keyring
+ctime=$(date +%s)
+mtime=0
+lock-on-idle=false
+lock-after=false
+EOF
+
+cat << EOF | tee "$DEFAULT_FILE"
```
Comment (y0no) [inline install/login/default-keyring.sh:14]: Same here

Comment (ryanrhughes) [reply install/login/default-keyring.sh:14]: Good catch. Thank you.

**Comment by nightdevil00** [comment]
setting the keyring with no password makes SDDM unable to login to uwsm session and manual intervention is required. I had to enable multi-users.target.  I used this to go around the issue and be able to login. I was on dev branch, no option from sddm brought me to desktop, login password did not work as keyring was blank.  I have a Lenovo thinkbook 15p 
IMG_8039

[fix_sddm_autologin.sh](https://github.com/user-attachments/files/22784243/fix_sddm_autologin.sh)

**Comment by celsobenedetti** [comment]
> [fix_sddm_autologin.sh](https://github.com/user-attachments/files/22784243/fix_sddm_autologin.sh)

Legit fixed my issue (default sddm login page, as shown in the picture above, and described here #2603).
Thank you sir.
